dist: bionic
language: go

go:
  - '1.13'

before_install:
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/golang/protobuf/protoc-gen-go

addons:
  apt:
    update: true
    packages:
      - protobuf-compiler

script:
  - make check
  - make
